line-length = 180
target-version = "py311"

# Linting rule selection
select = ["E", "W", "F", "C", "R"]
ignore = ["E501"]  # Ignore long line errors

# Exclude files from checks
exclude = [
    "**/*.ipynb"
]