name: madras-data-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py
          ruff: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black mypy
          pip install -r requirements.txt
      - name: Analysing the code with BLACK
        run: |
          black --diff $(git ls-files '*.py')
      - name: Analysing the code with MYPY
        run: |
          mypy --strict $(git ls-files '*.py')
    